// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasjCzS006kZMO389u2GbvDlKUSUkrujU',
    appId: '1:403918040125:android:f012f6fbe5865153fbce54',
    messagingSenderId: '403918040125',
    projectId: 'myflowertree-customer',
    storageBucket: "myflowertree-customer.appspot.com"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyAJX9GAFZIdYzMgb2kuG6m2s2dCiZbaY04',
      appId: '1:403918040125:ios:595eed3829af7010fbce54',
      messagingSenderId: '403918040125',
      projectId: 'myflowertree-customer',
      storageBucket: "myflowertree-customer.appspot.com"
  );

}
